import { Pet, AdoptionStats } from './types';

export const PETS: Pet[] = [
  {
    id: '1',
    name: 'Coquí',
    breed: 'Mixed Breed',
    age: '2 years',
    gender: 'Male',
    size: 'Medium',
    description: 'Coquí is a high-energy rescue who loves beach days in Luquillo. He is excellent with kids and knows basic commands in both Spanish and English!',
    image: 'https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&q=80&w=800',
    tags: ['Active', 'Family Friendly', 'Smart'],
    location: 'San Juan',
    isAdopted: false,
    energyLevel: 'High',
    trainingLevel: 'Intermediate',
    idealFor: 'Active Families',
    isHouseTrained: 'Yes',
  },
  {
    id: '2',
    name: 'Luna',
    breed: 'Potcake Mix',
    age: '4 months',
    gender: 'Female',
    size: 'Small',
    description: 'Sweet little Luna was found near El Yunque. She is calm, affectionate, and looking for a quiet home to grow up in.',
    image: 'https://images.unsplash.com/photo-1605639156481-244775d6f803?auto=format&fit=crop&q=80&w=800',
    tags: ['Puppy', 'Calm', 'Sweet', 'Good with Cats'],
    location: 'Rio Grande',
    isAdopted: false,
    energyLevel: 'Low',
    trainingLevel: 'Basic',
    idealFor: 'Quiet Households',
    isHouseTrained: 'Working on it',
  },
  {
    id: '3',
    name: 'Boricua',
    breed: 'Labrador Mix',
    age: '5 years',
    gender: 'Male',
    size: 'Large',
    description: 'Boricua is the ultimate companion. Loyal to a fault and loves naps in the shade. He is a gentle soul waiting for a porch to call his own.',
    image: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&q=80&w=800',
    tags: ['Loyal', 'Gentle', 'Senior-ish'],
    location: 'Ponce',
    isAdopted: false,
    energyLevel: 'Low',
    trainingLevel: 'Advanced',
    idealFor: 'Seniors or Relaxed Homes',
    isHouseTrained: 'Yes',
  },
  {
    id: '8',
    name: 'Cutie',
    breed: 'Labrador Mix',
    age: '11 years',
    gender: 'Female',
    size: 'Large',
    description: 'Cutie is the definition of a gentle soul. With her wise, soulful eyes and sweet pink nose, she is looking for a peaceful retirement home in San Juan. She is incredibly calm, house-trained, and gets along wonderfully with other dogs.',
    // Using direct Google Drive link for reliable hosting
    image: 'https://lh3.googleusercontent.com/d/1zSZFeE0czQr3q3Iz24U9KODdMdDe_qt6',
    imagePosition: 'object-top',
    tags: ['Senior', 'Gentle', 'San Juan Resident', 'Calm'],
    location: 'San Juan',
    isAdopted: false,
    energyLevel: 'Low',
    trainingLevel: 'Advanced',
    idealFor: 'Seniors / Relaxed Families',
    isHouseTrained: 'Yes',
  },
  {
    id: '7',
    name: 'Chico',
    breed: 'Mixed Breed',
    age: '1.5 years',
    gender: 'Male',
    size: 'Medium',
    description: 'Found wandering near the historic El Morro fort in Old San Juan, Chico is a true survivor with a heart of gold. He is incredibly playful and has a tail that never stops wagging.',
    image: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&q=80&w=800',
    tags: ['Playful', 'Kid Friendly', 'Solo Pet'],
    location: 'Old San Juan',
    isAdopted: false,
    energyLevel: 'Very High',
    trainingLevel: 'Basic',
    idealFor: 'Active Owners / Only Pet',
    isHouseTrained: 'Working on it',
  },
  {
    id: '4',
    name: 'Mango',
    breed: 'Coconut Hound',
    age: '1 year',
    gender: 'Female',
    size: 'Medium',
    description: 'Mango is as sweet as the fruit! She has a unique brindled coat and loves playing fetch. She is fully vaccinated and ready to travel.',
    image: 'https://images.unsplash.com/photo-1583337130417-3346a1be7dee?auto=format&fit=crop&q=80&w=800',
    tags: ['Playful', 'Healthy', 'Good with Dogs'],
    location: 'Mayagüez',
    isAdopted: false,
    energyLevel: 'High',
    trainingLevel: 'Basic',
    idealFor: 'Multi-dog Households',
    isHouseTrained: 'Yes',
  },
  {
    id: '5',
    name: 'Pucho',
    breed: 'Chihuahua Mix',
    age: '3 years',
    gender: 'Male',
    size: 'Small',
    description: 'Don\'t let his size fool you, Pucho has a big personality! He loves being the center of attention and is a great apartment dog.',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&q=80&w=800',
    tags: ['Brave', 'Apartment Friendly', 'Alert'],
    location: 'Caguas',
    isAdopted: false,
    energyLevel: 'Medium',
    trainingLevel: 'Basic',
    idealFor: 'Apartment Dwellers',
    isHouseTrained: 'Yes',
  },
  {
    id: '6',
    name: 'Sol',
    breed: 'Golden Mix',
    age: '2 years',
    gender: 'Female',
    size: 'Medium',
    description: 'Sol literally radiates happiness. She was rescued from a busy highway and is so grateful for every pat she gets.',
    image: 'https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&q=80&w=800',
    tags: ['Grateful', 'Friendly', 'Affectionate', 'Good with Cats'],
    location: 'Dorado',
    isAdopted: false,
    energyLevel: 'Medium',
    trainingLevel: 'Intermediate',
    idealFor: 'First-time Owners',
    isHouseTrained: 'Yes',
  }
];

export const SHELTER_STATS: AdoptionStats[] = [
  { month: 'Jan', adoptions: 45, rescues: 50 },
  { month: 'Feb', adoptions: 52, rescues: 48 },
  { month: 'Mar', adoptions: 48, rescues: 60 },
  { month: 'Apr', adoptions: 61, rescues: 55 },
  { month: 'May', adoptions: 55, rescues: 65 },
  { month: 'Jun', adoptions: 70, rescues: 72 },
];
